# Generated by Django 4.2.5 on 2023-12-22 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'branch',
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    'number',
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ('balance', models.FloatField(default=0)),
                ('limits', models.FloatField(default=0)),
                ('home_screen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('description', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('description', models.CharField(max_length=30)),
                (
                    'code',
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    'icon',
                    models.ImageField(blank=True, null=True, upload_to='img/'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'icon',
                    models.ImageField(blank=True, null=True, upload_to='img/'),
                ),
                ('description', models.CharField(max_length=30)),
                ('limits', models.FloatField(default=0)),
                ('expiration_day', models.IntegerField()),
                ('closing_day', models.IntegerField()),
                ('home_screen', models.BooleanField(default=False)),
                (
                    'account',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='statement.account',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[('entrada', 'Entrada'), ('saida', 'Saída')],
                        default='saida',
                        max_length=7,
                    ),
                ),
                ('description', models.CharField(max_length=30)),
                (
                    'color',
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    'icon',
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ('ignore', models.BooleanField(blank=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                (
                    'id',
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ('description', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('description', models.CharField(max_length=20)),
                (
                    'icon',
                    models.ImageField(blank=True, null=True, upload_to='img/'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('release_date', models.DateField()),
                ('description', models.CharField(max_length=50)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('description', models.CharField(max_length=30)),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='statement.category',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('release_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('description', models.CharField(max_length=50)),
                ('value', models.FloatField(default=0)),
                ('installments_number', models.IntegerField(default=0)),
                ('paid', models.IntegerField(default=0)),
                ('fixed', models.BooleanField(default=False)),
                ('annual', models.BooleanField(default=False)),
                ('observation', models.TextField(blank=True, null=True)),
                ('remember', models.BooleanField(default=False)),
                (
                    'type',
                    models.CharField(
                        choices=[('entrada', 'Entrada'), ('saida', 'Saída')],
                        default='saida',
                        max_length=7,
                    ),
                ),
                ('effected', models.BooleanField(default=False)),
                ('home_screen', models.BooleanField(default=True)),
                (
                    'account',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='statement.account',
                    ),
                ),
                (
                    'card',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='statement.card',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='statement.category',
                    ),
                ),
                (
                    'currency',
                    models.ForeignKey(
                        default='BRL',
                        on_delete=django.db.models.deletion.PROTECT,
                        to='statement.currency',
                    ),
                ),
                (
                    'installment',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='statement.installment',
                    ),
                ),
                (
                    'subcategory',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='statement.subcategory',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='NextMonthView',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('day', models.IntegerField()),
                ('active', models.BooleanField(blank=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='flag',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='statement.flag',
            ),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='statement.bank',
            ),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='statement.accounttype',
            ),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
