# Generated by Django 5.0 on 2023-12-29 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0002_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['version']},
        ),
    ]
