# Generated by Django 4.2.5 on 2024-01-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0003_alter_version_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='file_handler_conf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='file_handler_conf',
            field=models.TextField(blank=True, null=True),
        ),
    ]
