# Generated by Django 4.2.5 on 2026-02-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0004_rename_installment_release_date_to_posted_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['posted_date']},
        ),
    ]
