# Generated by Django 4.2.5 on 2024-04-13 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statement', '0005_fixedexpenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('description', models.CharField(max_length=70)),
                ('value', models.FloatField()),
                ('limit_date', models.DateField()),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name='version',
            options={},
        ),
        migrations.AddField(
            model_name='version',
            name='date',
            field=models.DateField(default='2017-01-01'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Portion',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                (
                    'dream',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='statement.dream',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
