# Generated by Django 4.2.5 on 2026-05-12 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0005_alter_transaction_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='value',
        ),
        migrations.AddField(
            model_name='dream',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('paused', 'Pausado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='dream',
            name='target_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='dream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='statement.dream'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='limit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
