# Generated by Django 4.2.5 on 2024-04-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0006_dream_alter_version_options_portion'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='date',
            field=models.DateField(default='2017-01-01'),
            preserve_default=False,
        ),
    ]
