# Generated by Django 4.2.5 on 2024-08-11 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0007_alter_transaction_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FixedIncome',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('principal', models.FloatField()),
                ('investment_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('contractual_rate', models.FloatField()),
                (
                    'account',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statement.account'),
                ),
                (
                    'index',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statement.index'),
                ),
            ],
        ),
    ]
