# Generated by Django 4.2.5 on 2026-05-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0007_loan_loanentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Anotações'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='status',
            field=models.CharField(
                choices=[
                    ('active', 'Ativo'),
                    ('paused', 'Pausado'),
                    ('completed', 'Realizado'),
                    ('cancelled', 'Cancelado'),
                ],
                default='active',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(
                choices=[
                    ('active', 'Ativo'),
                    ('inactive', 'Finalizado'),
                ],
                default='active',
                max_length=10,
            ),
        ),
    ]
