# Generated by Django 4.2.5 on 2025-02-09 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statement', '0007_alter_transaction_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedIncomeSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('bcb_id', models.IntegerField(blank=True, null=True)),
                ('first_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexHistoricalSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.FloatField()),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statement.index')),
            ],
        ),
        migrations.CreateModel(
            name='IndexHistoricalSeriesServices',
            fields=[
                ('indexhistoricalseries_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statement.indexhistoricalseries')),
            ],
            bases=('statement.indexhistoricalseries',),
        ),
        migrations.CreateModel(
            name='IndexServices',
            fields=[
                ('index_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statement.index')),
            ],
            bases=('statement.index',),
        ),
        migrations.CreateModel(
            name='FixedIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.FloatField()),
                ('investment_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('contractual_rate', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statement.account')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statement.index')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statement.fixedincomesecurity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
