# Generated by Django 4.2.5 on 2025-03-01 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0008_fixedincomesecurity_index_indexhistoricalseries_and_more'),
    ]

    operations = [
        migrations.RunSQL('DROP TABLE IF EXISTS django_q_schedule;'),
        migrations.RunSQL('DROP TABLE IF EXISTS django_q_task;'),
        migrations.RunSQL('DROP TABLE IF EXISTS django_q_failure;'),
        migrations.RunSQL('DROP TABLE IF EXISTS django_q_success;'),
        migrations.RunSQL('DROP TABLE IF EXISTS django_q_ormq;'),
    ]
