# Generated by Django 4.2.5 on 2024-08-11 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statement', '0008_index_fixedincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedincome',
            name='user',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
    ]
