# Generated by Django 4.2.5 on 2026-05-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0008_dream_notes_alter_dream_status_alter_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de conclusão'),
        ),
    ]
