# Generated by Django 4.2.5 on 2026-05-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0009_dream_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Anotações'),
        ),
    ]
