# Generated by Django 4.2.5 on 2025-03-07 15:09

from django.db import migrations


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0009_remove_django_q'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedincome',
            options={'ordering': ['investment_date']},
        ),
    ]
