# Generated by Django 4.2.5 on 2024-10-13 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0009_fixedincome_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='name',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='index',
            name='date',
        ),
        migrations.RemoveField(
            model_name='index',
            name='rate',
        ),
        migrations.CreateModel(
            name='IndexHistoricalSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statement.index')),
            ],
        ),
    ]
