# Generated by Django 4.2.5 on 2025-03-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0010_alter_fixedincome_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
