# Generated by Django 4.2.5 on 2024-10-13 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0010_rename_name_index_description_remove_index_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexHistoricalSeriesServices',
            fields=[
                ('indexhistoricalseries_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statement.indexhistoricalseries')),
            ],
            bases=('statement.indexhistoricalseries',),
        ),
        migrations.CreateModel(
            name='IndexServices',
            fields=[
                ('index_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statement.index')),
            ],
            bases=('statement.index',),
        ),
        migrations.RenameField(
            model_name='indexhistoricalseries',
            old_name='name',
            new_name='index',
        ),
    ]
