# Generated by Django 4.2.5 on 2026-05-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0010_loan_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_investment',
            field=models.BooleanField(default=False),
        ),
    ]
