# Generated by Django 4.2.5 on 2025-03-07 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statement', '0011_remove_category_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='VariableIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statement.account')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statement.ticker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ticker__code'],
            },
        ),
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('buy', 'Compra'), ('sell', 'Venda')], max_length=10)),
                ('date', models.DateField()),
                ('broker_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capital_gain_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('variable_income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statement.variableincome')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
