# Generated by Django 4.2.5 on 2026-07-17 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statement', '0011_subcategory_is_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardnumber',
            name='visible_to',
            field=models.ManyToManyField(blank=True, related_name='visible_card_numbers', to=settings.AUTH_USER_MODEL),
        ),
    ]
