# Generated by Django 4.2.5 on 2024-10-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0011_indexhistoricalseriesservices_indexservices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='bcb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='first_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
