# Generated by Django 4.2.5 on 2025-03-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0012_sector_ticker_variableincome_assettransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='user',
        ),
    ]
