# Generated by Django 4.2.5 on 2026-05-24 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('asset_type', models.CharField(choices=[('fixed_income', 'Renda fixa'), ('variable_income', 'Renda variável'), ('crypto', 'Cripto'), ('currency', 'Moeda'), ('other', 'Outro')], max_length=30)),
                ('income_behavior', models.CharField(choices=[('none', 'Não gera renda'), ('interest', 'Juros/rendimento'), ('dividend', 'Dividendos/proventos')], default='none', max_length=20)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset_type', 'description'],
                'unique_together': {('description', 'symbol', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('bank', 'Banco'), ('broker', 'Corretora'), ('exchange', 'Exchange'), ('wallet', 'Carteira'), ('other', 'Outro')], default='broker', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['description'],
                'unique_together': {('description', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=140)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('closed', 'Encerrado')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='investments.asset')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='investments.broker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset__asset_type', 'description'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('aporte', 'Aporte/Aplicação'), ('resgate', 'Resgate'), ('rendimento', 'Rendimento/Provento'), ('atualizacao', 'Atualização de valor'), ('custo', 'Taxa/Imposto')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
