# Generated by Django 4.2.5 on 2026-05-28 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0010_loan_notes'),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttransaction',
            name='operation_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='statement_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investment_transaction', to='statement.transaction'),
        ),
    ]
