# Generated by Django 4.2.5 on 2026-06-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_create_default_wallets'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttransaction',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
