# Generated by Django 4.2.5 on 2026-02-22 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='next_month_day',
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)],
            ),
        ),
    ]
